steps:
- name: 'python:3.9'
  entrypoint: pip
  args: ['install', '-r', 'requirements.txt']

- name: 'python:3.9'
  entrypoint: python
  args: ['pipeline.py']
  env:
    - 'PROJECT_ID=involuted-tuner-441406-a9'
    - 'LOCATION=us-central1'
    - 'BUCKET_URI=gs://mlops-01-pipeline/pipeline_root_1'
    - 'GOOGLE_CLOUD_PROJECT=involuted-tuner-441406-a9'

substitutions:
  _PYTHON_FILE: pipeline1.py

options:
  logging: CLOUD_LOGGING_ONLY